### PR TITLE
Feature frontend authorization pull to frontend branch.

### PR DESCRIPTION
**Pull request by JuliusJauga**
Added authorization, planning to add contributions next.

### CODE REVIEW

**Comment by JuliusJauga** [comment]
web-api-backend branch also needs to be pulled here for everything to work properly.

**Review by tikis23 — APPROVED** [review]
nice

**Comment by RokasBal** [comment]
Everything looks okay to me

**Review by AurelijusLuksas — APPROVED** [review]
Seems okay, not need to look really carefully, because not merging to main.

**Pull request merged**
