### PR TITLE
Logging to database.

### PR DESCRIPTION
**Pull request by JuliusJauga**
Check if this works @RokasBal

### CODE REVIEW

**Comment by RokasBal** [comment]
It does not seem to work for me. I attempted to build it, but I get this error:

`/home/rokas/Documents/Uni/CSharp/FlashRead/server/server/src/Exceptions/ExceptionMiddleware.cs(10,38): error CS0246: The type or namespace name 'FlashDbContext' could not be found (are you missing a using directive or an assembly reference?) [/home/rokas/Documents/Uni/CSharp/FlashRead/server/server/server.csproj]`

**Comment by JuliusJauga** [comment]
For now lets just make the logging to a local file.

**Comment by JuliusJauga** [comment]
Nevermind, its logging to database.

**Review by RokasBal — APPROVED** [review]
Looks like the issues are fixed now. Both of the implemented exceptions seem to log correctly.

**Pull request merged**
