### PR TITLE
Frontend merge to main

### PR DESCRIPTION
**Pull request by AurelijusLuksas**
Improved front, switched to changing pages instead of individual divs.

### CODE REVIEW

**Review by tikis23 — CHANGES_REQUESTED** [review]
Fix linter erros before merging

**Comment by JuliusJauga** [comment]
Can you remove unused imports?

**Review by JuliusJauga — CHANGES_REQUESTED** [review]
Can you delete unused imports?

**Comment by AurelijusLuksas** [comment]
Fixed.

**Review by tikis23 — APPROVED** [review]
👍

**Review by JuliusJauga — APPROVED** [review]

**Pull request merged**
