### PR TITLE
Frontend

### PR DESCRIPTION
**Pull request by AurelijusLuksas**
good luck checking this :)

### CODE REVIEW

**Comment by JuliusJauga** [comment]
2.5 million new lines, hard work paid off.

**Comment by AurelijusLuksas** [comment]
good job, remove the checks so we pass them

**Review by RokasBal — APPROVED** [review]
Good work, but will need to fix bugs with theme loading later.

**Comment by JuliusJauga** [comment]
Need to add unit tests ASAP.

**Comment by AurelijusLuksas** [comment]
also run lint and fix problems

**Comment by JuliusJauga** [comment]
image

**Comment by AurelijusLuksas** [comment]
just like my family tree

**Comment by tikis23** [comment]
Checks should pass, but everything works i guess. We can fix them another time

**Comment by JuliusJauga** [comment]
> Checks should pass, but everything works i guess. We can fix them another time

Yes we just rebase from the main branch now, before BETA release the main will get updated again.

**Review by tikis23 — APPROVED** [review]

**Review by JuliusJauga — APPROVED** [review]

**Comment by AurelijusLuksas** [comment]
here we go.

**Pull request merged**
